import 'package:flutter/material.dart';import 'package:team_grab/core/app_export.dart';import 'package:team_grab/widgets/app_bar/appbar_leading_image.dart';import 'package:team_grab/widgets/app_bar/appbar_subtitle.dart';import 'package:team_grab/widgets/app_bar/appbar_title.dart';import 'package:team_grab/widgets/app_bar/custom_app_bar.dart';import 'package:team_grab/widgets/custom_elevated_button.dart';class PaymentScreen extends StatelessWidget {const PaymentScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 23.v), child: Column(children: [_buildMustangShelbyGT(context), SizedBox(height: 17.v), Align(alignment: Alignment.centerLeft, child: Text("Charge", style: theme.textTheme.titleMedium)), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(right: 1.h), child: _buildVat5(context, vatFive: "Mustang/per hours", price: "200")), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(right: 1.h), child: _buildVat5(context, vatFive: "Vat (5%)", price: "20")), SizedBox(height: 5.v), Padding(padding: EdgeInsets.only(right: 1.h), child: _buildVat5(context, vatFive: "Promo Code", price: "-5")), SizedBox(height: 3.v), Divider(color: appTheme.gray20001), SizedBox(height: 13.v), _buildVat8(context), SizedBox(height: 30.v), _buildFrame(context), SizedBox(height: 20.v), Padding(padding: EdgeInsets.only(right: 1.h), child: _buildPaymentCard(context)), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(right: 1.h), child: _buildPaymentCard(context)), SizedBox(height: 8.v), _buildPaymentCard3(context), SizedBox(height: 8.v), _buildPaymentCard4(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildConfirmRide(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 8.h, top: 14.v, bottom: 17.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 5.h), child: Row(children: [AppbarSubtitle(text: "Back", margin: EdgeInsets.only(bottom: 3.v)), AppbarTitle(text: "Payment", margin: EdgeInsets.only(left: 79.h, top: 1.v))]))); } 
/// Section Widget
Widget _buildMustangShelbyGT(BuildContext context) { return Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.all(11.h), decoration: AppDecoration.outlineAmberA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 2.v, bottom: 1.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Mustang Shelby GT", style: theme.textTheme.titleMedium), SizedBox(height: 3.v), Row(children: [CustomImageView(imagePath: ImageConstant.imgVectorYellow700, height: 16.adaptSize, width: 16.adaptSize, margin: EdgeInsets.only(top: 3.v, bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 7.h), child: Text("4.9 (531 reviews)", style: CustomTextStyles.titleSmallGray400))])])), CustomImageView(imagePath: ImageConstant.imgImage3, height: 54.v, width: 93.h, margin: EdgeInsets.only(right: 2.h))])); } 
/// Section Widget
Widget _buildVat8(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 5.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Total", style: theme.textTheme.bodyMedium), Text("215", style: theme.textTheme.bodyMedium)])); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 4.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 1.v), child: Text("Select payment method", style: CustomTextStyles.titleMedium18)), Padding(padding: EdgeInsets.only(bottom: 3.v), child: Text("View All ", style: CustomTextStyles.titleMediumAmber500))])); } 
/// Section Widget
Widget _buildPaymentCard3(BuildContext context) { return Opacity(opacity: 0.4, child: Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 5.v), decoration: AppDecoration.outlineAmberA4001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgPaymentIndigo900, height: 35.v, width: 45.h, margin: EdgeInsets.only(top: 5.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 13.h, top: 4.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("mailaddress@mail.com", style: theme.textTheme.titleMedium), Text("Expires: 12/26", style: CustomTextStyles.titleSmallGray400)]))]))); } 
/// Section Widget
Widget _buildPaymentCard4(BuildContext context) { return Opacity(opacity: 0.4, child: Container(margin: EdgeInsets.only(right: 1.h), padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 7.v), decoration: AppDecoration.outlineAmberA4001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgPaymentBlack900, height: 43.v, width: 45.h, margin: EdgeInsets.only(bottom: 1.v)), Padding(padding: EdgeInsets.only(left: 11.h, top: 8.v, bottom: 10.v), child: Text("Cash", style: theme.textTheme.titleMedium))]))); } 
/// Section Widget
Widget _buildConfirmRide(BuildContext context) { return CustomElevatedButton(text: "Confirm Ride", margin: EdgeInsets.only(left: 15.h, right: 16.h, bottom: 42.v)); } 
/// Common widget
Widget _buildVat5(BuildContext context, {required String vatFive, required String price, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [RichText(text: TextSpan(children: [TextSpan(text: "Vat ", style: theme.textTheme.bodyMedium), TextSpan(text: "(5%)", style: CustomTextStyles.bodySmallGray700)]), textAlign: TextAlign.left), Text(price, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.gray700))]); } 
/// Common widget
Widget _buildPaymentCard(BuildContext context) { return Opacity(opacity: 0.4, child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 5.v), decoration: AppDecoration.outlineAmberA4001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(children: [CustomImageView(imagePath: ImageConstant.imgPayment, height: 35.v, width: 45.h, margin: EdgeInsets.only(top: 5.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 13.h, top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("**** **** **** 8970", style: theme.textTheme.titleMedium), Text("Expires: 12/26", style: CustomTextStyles.titleSmallGray400)]))]))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
