import 'package:flutter/material.dart';import 'package:team_grab/core/app_export.dart';import 'package:team_grab/widgets/app_bar/appbar_leading_image.dart';import 'package:team_grab/widgets/app_bar/appbar_subtitle.dart';import 'package:team_grab/widgets/app_bar/custom_app_bar.dart';import 'package:team_grab/widgets/custom_elevated_button.dart';import 'package:team_grab/widgets/custom_icon_button.dart';class ForgetPasswordScreen extends StatelessWidget {const ForgetPasswordScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 14.h, vertical: 22.v), child: Column(children: [Text("Forgot Password", style: theme.textTheme.headlineSmall), SizedBox(height: 7.v), Container(width: 282.h, margin: EdgeInsets.only(left: 45.h, right: 36.h), child: Text("Select which contact details should we use to reset your password", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyLargeGray500.copyWith(height: 1.50))), SizedBox(height: 33.v), _buildMessageSvgrepoCom(context), SizedBox(height: 16.v), _buildViaEmail(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinue(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 8.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitle(text: "Back", margin: EdgeInsets.only(left: 5.h))); } 
/// Section Widget
Widget _buildMessageSvgrepoCom(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h, right: 1.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 11.v), decoration: AppDecoration.outlineAmberA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(7.h), decoration: IconButtonStyleHelper.outlineAmberA, child: CustomImageView(imagePath: ImageConstant.imgMessageSvgrepoCom))), Padding(padding: EdgeInsets.only(left: 8.h, bottom: 9.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Via SMS", style: CustomTextStyles.titleSmallGray400), Text("***** ***70", style: theme.textTheme.titleMedium)]))])); } 
/// Section Widget
Widget _buildViaEmail(BuildContext context) { return Container(margin: EdgeInsets.only(left: 2.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.outlineAmber.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(13.h), decoration: IconButtonStyleHelper.outlineAmberA, child: CustomImageView(imagePath: ImageConstant.imgGroup39335))), Padding(padding: EdgeInsets.only(left: 8.h, bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Via Email", style: CustomTextStyles.titleSmallGray400), Text("**** **** **** xyz@xyz.com", style: theme.textTheme.titleMedium)]))])); } 
/// Section Widget
Widget _buildContinue(BuildContext context) { return CustomElevatedButton(text: "Continue", margin: EdgeInsets.only(left: 17.h, right: 16.h, bottom: 50.v)); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
