import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:team_grab/core/app_export.dart';import 'package:team_grab/widgets/app_bar/appbar_leading_image.dart';import 'package:team_grab/widgets/app_bar/appbar_subtitle.dart';import 'package:team_grab/widgets/app_bar/custom_app_bar.dart';import 'package:team_grab/widgets/custom_elevated_button.dart';class ThankYouScreen extends StatelessWidget {const ThankYouScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 13.v), child: Column(children: [SizedBox(height: 146.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 80.h, right: 83.h, bottom: 5.v), child: Column(children: [Container(height: 124.adaptSize, width: 124.adaptSize, padding: EdgeInsets.symmetric(horizontal: 34.h, vertical: 41.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup6476), fit: BoxFit.cover)), child: CustomImageView(imagePath: ImageConstant.imgCheck, height: 41.v, width: 55.h, alignment: Alignment.center)), SizedBox(height: 24.v), Text("Thank you", style: CustomTextStyles.titleLarge20), SizedBox(height: 3.v), SizedBox(width: 229.h, child: Text("Your booking has been placed sent to \nMd. Sharif Ahmed", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.labelLargeGray700.copyWith(height: 1.50)))]))))])), bottomNavigationBar: _buildConfirmRide(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 8.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitle(text: "Back", margin: EdgeInsets.only(left: 5.h))); } 
/// Section Widget
Widget _buildConfirmRide(BuildContext context) { return CustomElevatedButton(text: "Confirm Ride", margin: EdgeInsets.only(left: 16.h, right: 15.h, bottom: 34.v)); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
