import 'package:flutter/material.dart';import 'package:team_grab/core/app_export.dart';import 'package:team_grab/widgets/app_bar/appbar_leading_image.dart';import 'package:team_grab/widgets/app_bar/appbar_subtitle.dart';import 'package:team_grab/widgets/app_bar/custom_app_bar.dart';import 'package:team_grab/widgets/custom_icon_button.dart';class CallingScreen extends StatelessWidget {const CallingScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.only(top: 141.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgEllipse43, height: 100.adaptSize, width: 100.adaptSize, radius: BorderRadius.circular(50.h)), SizedBox(height: 20.v), Text("Sergio Ramasis", style: theme.textTheme.headlineMedium), SizedBox(height: 2.v), Text("Calling....", style: CustomTextStyles.titleSmallGray400), SizedBox(height: 5.v)])), bottomNavigationBar: _buildBack(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 8.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), title: AppbarSubtitle(text: "Back", margin: EdgeInsets.only(left: 5.h))); } 
/// Section Widget
Widget _buildBack(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 17.h, right: 17.h, bottom: 40.v), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.symmetric(vertical: 10.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(13.h), decoration: IconButtonStyleHelper.fillAmberTL25, child: CustomImageView(imagePath: ImageConstant.imgBack))), Padding(padding: EdgeInsets.symmetric(vertical: 10.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(13.h), decoration: IconButtonStyleHelper.fillAmberTL25, child: CustomImageView(imagePath: ImageConstant.imgGroup33))), CustomIconButton(height: 70.adaptSize, width: 70.adaptSize, padding: EdgeInsets.all(13.h), decoration: IconButtonStyleHelper.fillGreen, child: CustomImageView(imagePath: ImageConstant.imgCall)), Padding(padding: EdgeInsets.symmetric(vertical: 10.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(13.h), decoration: IconButtonStyleHelper.fillAmberTL25, child: CustomImageView(imagePath: ImageConstant.imgVideoCamera))), Padding(padding: EdgeInsets.symmetric(vertical: 10.v), child: CustomIconButton(height: 50.adaptSize, width: 50.adaptSize, padding: EdgeInsets.all(13.h), decoration: IconButtonStyleHelper.fillAmberTL25, child: CustomImageView(imagePath: ImageConstant.imgLink)))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
