import 'package:flutter/material.dart';import 'package:team_grab/core/app_export.dart';import 'package:team_grab/widgets/app_bar/appbar_leading_image.dart';import 'package:team_grab/widgets/app_bar/appbar_subtitle.dart';import 'package:team_grab/widgets/app_bar/appbar_title.dart';import 'package:team_grab/widgets/app_bar/custom_app_bar.dart';import 'package:team_grab/widgets/custom_elevated_button.dart';import 'package:team_grab/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class RequestRentOneScreen extends StatelessWidget {RequestRentOneScreen({Key? key}) : super(key: key);

TextEditingController paymentController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 15.v), child: Column(children: [SizedBox(height: 20.v), Expanded(child: SingleChildScrollView(child: Padding(padding: EdgeInsets.only(left: 4.h, right: 8.h, bottom: 5.v), child: Column(children: [_buildLineTwentyFour(context), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 15.h), child: _buildVat5(context, vatFive: "Giá cước", price: "200")), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 15.h), child: _buildVat5(context, vatFive: "Vat (5%)", price: "20")), SizedBox(height: 6.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 15.h), child: _buildVat5(context, vatFive: "Mã khuyến mãi", price: "-5")), SizedBox(height: 12.v), Padding(padding: EdgeInsets.only(left: 4.h, right: 15.h), child: _buildVat5(context, vatFive: "Hình thức thanh toán", price: "Xem tất cả")), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 11.h, right: 8.h), child: _buildPaymentCard(context)), SizedBox(height: 30.v), Padding(padding: EdgeInsets.only(left: 11.h, right: 8.h), child: _buildPaymentCard(context)), SizedBox(height: 30.v), _buildPaymentCard3(context), SizedBox(height: 39.v), Padding(padding: EdgeInsets.only(left: 12.h, right: 7.h), child: CustomTextFormField(controller: paymentController, hintText: "Tiền mặt", hintStyle: theme.textTheme.titleMedium!, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(15.h, 8.v, 11.h, 9.v), child: CustomImageView(imagePath: ImageConstant.imgPaymentBlack900, height: 43.v, width: 45.h)), prefixConstraints: BoxConstraints(maxHeight: 60.v), contentPadding: EdgeInsets.only(top: 17.v, right: 30.h, bottom: 17.v)))]))))])), bottomNavigationBar: _buildXcNhnChuyni(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 8.h, top: 14.v, bottom: 17.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 5.h), child: Row(children: [AppbarSubtitle(text: "Trở lại", margin: EdgeInsets.only(bottom: 2.v)), AppbarTitle(text: "Đặt xe", margin: EdgeInsets.only(left: 85.h))]))); } 
/// Section Widget
Widget _buildLineTwentyFour(BuildContext context) { return SizedBox(height: 134.v, width: 381.h, child: Stack(alignment: Alignment.topLeft, children: [Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 23.h), child: SizedBox(height: 71.v, child: VerticalDivider(width: 1.h, thickness: 1.v, color: appTheme.amberA400, indent: 19.h)))), Align(alignment: Alignment.topLeft, child: Padding(padding: EdgeInsets.only(left: 11.h), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgLocationRed500, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("Vị trí của bạn", style: theme.textTheme.titleMedium))]), Align(alignment: Alignment.centerRight, child: Text("227 Đ.Nguyễn Văn cừ,Quận 5,TPHCM", style: theme.textTheme.bodySmall))]))), Align(alignment: Alignment.bottomCenter, child: Padding(padding: EdgeInsets.only(left: 11.h, bottom: 24.v), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [CustomImageView(imagePath: ImageConstant.imgLocationAmberA400, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 6.h), child: Text("MINISTOP", style: theme.textTheme.titleMedium)), Spacer(), Padding(padding: EdgeInsets.only(bottom: 2.v), child: Text("4.0km", style: CustomTextStyles.titleSmallGray700))]), SizedBox(height: 1.v), Padding(padding: EdgeInsets.only(left: 30.h), child: Text("19-21 Đ. Nguyễn Thiện Thuật,Quận 3,TPHCM", style: theme.textTheme.bodySmall))]))), Align(alignment: Alignment.bottomLeft, child: Text("Tổng", style: theme.textTheme.titleMedium))])); } 
/// Section Widget
Widget _buildPaymentCard3(BuildContext context) { return Opacity(opacity: 0.4, child: Container(margin: EdgeInsets.only(left: 11.h, right: 8.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 5.v), decoration: AppDecoration.outlineAmberA4001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisSize: MainAxisSize.max, children: [CustomImageView(imagePath: ImageConstant.imgPaymentOnprimary, height: 35.v, width: 45.h, margin: EdgeInsets.only(top: 5.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 13.h, top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("Ví điện tử", style: theme.textTheme.titleMedium), Text("349", style: CustomTextStyles.titleSmallGray400)]))]))); } 
/// Section Widget
Widget _buildXcNhnChuyni(BuildContext context) { return CustomElevatedButton(text: "Xác nhận chuyến đi", margin: EdgeInsets.only(left: 15.h, right: 16.h, bottom: 27.v)); } 
/// Common widget
Widget _buildVat5(BuildContext context, {required String vatFive, required String price, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [RichText(text: TextSpan(children: [TextSpan(text: "Vat ", style: theme.textTheme.bodyMedium), TextSpan(text: "(5%)", style: CustomTextStyles.bodySmallGray700)]), textAlign: TextAlign.left), Text(price, style: theme.textTheme.bodyMedium!.copyWith(color: appTheme.gray700))]); } 
/// Common widget
Widget _buildPaymentCard(BuildContext context) { return Opacity(opacity: 0.4, child: Container(padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 5.v), decoration: AppDecoration.outlineAmberA4001.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Row(mainAxisSize: MainAxisSize.max, children: [CustomImageView(imagePath: ImageConstant.imgPayment, height: 35.v, width: 45.h, margin: EdgeInsets.only(top: 5.v, bottom: 6.v)), Padding(padding: EdgeInsets.only(left: 13.h, top: 3.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("**** **** **** 8970", style: theme.textTheme.titleMedium), Text("Expires: 12/26", style: CustomTextStyles.titleSmallGray400)]))]))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
