import 'package:flutter/material.dart';import 'package:team_grab/core/app_export.dart';import 'package:team_grab/widgets/app_bar/appbar_leading_image.dart';import 'package:team_grab/widgets/app_bar/appbar_subtitle.dart';import 'package:team_grab/widgets/app_bar/appbar_title.dart';import 'package:team_grab/widgets/app_bar/custom_app_bar.dart';import 'package:team_grab/widgets/custom_elevated_button.dart';import 'package:team_grab/widgets/custom_outlined_button.dart';import 'package:team_grab/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class MessageScreen extends StatelessWidget {MessageScreen({Key? key}) : super(key: key);

TextEditingController messageController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 23.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgEllipse42, height: 36.adaptSize, width: 36.adaptSize, radius: BorderRadius.circular(18.h), margin: EdgeInsets.only(bottom: 18.v)), _buildGoodEvening(context)]), SizedBox(height: 8.v), Container(margin: EdgeInsets.only(left: 48.h, right: 66.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), decoration: AppDecoration.fillGray20001.copyWith(borderRadius: BorderRadiusStyle.customBorderBL16), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), SizedBox(width: 213.h, child: Text("Welcome to Car2go Customer \nService", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.57)))])), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 48.h), child: Text("8:29 pm", style: CustomTextStyles.bodySmallErrorContainer)), SizedBox(height: 28.v), _buildWelcomeToCar2goCustomer(context), SizedBox(height: 9.v), Align(alignment: Alignment.centerRight, child: Text("8:29 pm", style: CustomTextStyles.bodySmallErrorContainer)), SizedBox(height: 28.v), Padding(padding: EdgeInsets.only(right: 66.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgEllipse42, height: 36.adaptSize, width: 36.adaptSize, radius: BorderRadius.circular(18.h), margin: EdgeInsets.only(bottom: 40.v)), Expanded(child: Container(margin: EdgeInsets.only(left: 12.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 14.v), decoration: AppDecoration.fillGray20001.copyWith(borderRadius: BorderRadiusStyle.customBorderBL16), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Container(width: 213.h, margin: EdgeInsets.only(right: 3.h), child: Text("Welcome to Car2go Customer \nService", maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.57)))])))])), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(left: 47.h), child: Text("8:29 pm", style: CustomTextStyles.bodySmallErrorContainer)), SizedBox(height: 28.v), _buildWelcomeToCar2goCustomer1(context), SizedBox(height: 7.v), Align(alignment: Alignment.centerRight, child: Text("Just now", style: CustomTextStyles.bodySmallErrorContainer)), SizedBox(height: 5.v)])), bottomNavigationBar: _buildMessage1(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 32.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray900, margin: EdgeInsets.only(left: 8.h, top: 16.v, bottom: 15.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 5.h), child: Row(children: [AppbarSubtitle(text: "Back", margin: EdgeInsets.only(bottom: 1.v)), AppbarTitle(text: "Chat", margin: EdgeInsets.only(left: 97.h))]))); } 
/// Section Widget
Widget _buildGoodEvening(BuildContext context) { return CustomElevatedButton(width: 133.h, text: "Good Evening!", margin: EdgeInsets.only(left: 12.h), buttonStyle: CustomButtonStyles.fillGray, buttonTextStyle: theme.textTheme.bodyMedium!); } 
/// Section Widget
Widget _buildWelcomeToCar2goCustomer(BuildContext context) { return CustomOutlinedButton(text: "Welcome to Car2go Customer Service", margin: EdgeInsets.only(left: 63.h), buttonStyle: CustomButtonStyles.outlineAmberA, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildWelcomeToCar2goCustomer1(BuildContext context) { return CustomOutlinedButton(text: "Welcome to Car2go Customer Service", margin: EdgeInsets.only(left: 63.h), buttonStyle: CustomButtonStyles.outlineAmberA, alignment: Alignment.centerRight); } 
/// Section Widget
Widget _buildMessage(BuildContext context) { return Expanded(child: Padding(padding: EdgeInsets.only(left: 7.h), child: CustomTextFormField(controller: messageController, hintText: "Type your message", textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.fromLTRB(12.h, 14.v, 9.h, 14.v), child: CustomImageView(imagePath: ImageConstant.imgSmile, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 52.v), contentPadding: EdgeInsets.only(left: 16.h, top: 13.v, bottom: 13.v)))); } 
/// Section Widget
Widget _buildMessage1(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 15.h, right: 15.h, bottom: 31.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgPlus, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.symmetric(vertical: 14.v)), _buildMessage(context), CustomImageView(imagePath: ImageConstant.imgSend, height: 32.adaptSize, width: 32.adaptSize, margin: EdgeInsets.only(left: 7.h, top: 6.v, bottom: 13.v))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
